language: node_js
sudo: required
dist: trusty

node_js:
  - stable

script:
  - yarn run test

after_script:
  - yarn run test:coverage
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && yarn run demo:publish || false'
